<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9ygs9u\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9ygs9u/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC9ygs9u.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC9ygs9u\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC9ygs9u\appProdProjectContainer([
    'container.build_hash' => 'C9ygs9u',
    'container.build_id' => '3e8229c7',
    'container.build_time' => 1702386296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9ygs9u');
