<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpihxaq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpihxaq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOpihxaq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOpihxaq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOpihxaq\appProdProjectContainer([
    'container.build_hash' => 'Opihxaq',
    'container.build_id' => 'dd1e2cd0',
    'container.build_time' => 1701347199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpihxaq');
