<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTl1lbqd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTl1lbqd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTl1lbqd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTl1lbqd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTl1lbqd\appProdProjectContainer([
    'container.build_hash' => 'Tl1lbqd',
    'container.build_id' => '288f6086',
    'container.build_time' => 1706800927,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTl1lbqd');
